version: '3.4'

services:
  meufinanceiroapi:
    image: ${DOCKER_REGISTRY-}meufinanceiroapi
    build:
      context: .
      dockerfile: MeuFinanceiroApi/Dockerfile
    environment:
      Server: 192.168.1.4
      Database: MeuFinanceiro
      User: sa
      Password: 245809
    ports:
      - "65135:80"
