version: '3.4'

services:
  meufinanceiroapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Server=localhost
      - Database=MeuFinanceiro
      - User=sa
      - Password=mq9437?tn
    ports:
      - "65135:80"
networks:
  default:
   external:
    name: network-cluster-docker