USE master;
GO
CREATE DATABASE MeuFinanceiro
GO
USE MeuFinanceiro;
CREATE TABLE Despesas(
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Descricao VARCHAR(max) NULL,
    valor DECIMAL(12,2) NOT NULL,
    Data DATETIME NOT NULL  DEFAULT  GETDATE(),
    Pago BIT  NOT NULL DEFAULT 'N'
)
GO
CREATE TABLE Receitas(
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Descricao VARCHAR(max) NULL,
    valor DECIMAL(12,2) NOT NULL,
    Data DATETIME NOT NULL  DEFAULT  GETDATE(),
    Recebido BIT  NOT NULL DEFAULT 'N'
)

